In [1]:
import cvxpy as cp
import numpy as np

In [2]:
def loss_fn(X, Y, beta):
    return cp.norm2(cp.matmul(X, beta) - Y)**2

def regularizer(beta):
    return cp.norm1(beta)

def objective_fn(X, Y, beta, lambd):
    return loss_fn(X, Y, beta) + lambd * regularizer(beta)

def mse(X, Y, beta):
    return (1.0 / X.shape[0]) * loss_fn(X, Y, beta).value

In [3]:
def generate_data(m=100, n=20, sigma=5, density=0.2):
    "Generates data matrix X and observations Y."
    np.random.seed(1)
    beta_star = np.random.randn(n)
    idxs = np.random.choice(range(n), int((1-density)*n), replace=False)
    for idx in idxs:
        beta_star[idx] = 0
    X = np.random.randn(m,n)
    Y = X.dot(beta_star) + np.random.normal(0, sigma, size=m)
    return X, Y, beta_star

m = 100
n = 20
sigma = 5
density = 0.2

X, Y, _ = generate_data(m, n, sigma)
X_train = X[:50, :]
Y_train = Y[:50]
X_test = X[50:, :]
Y_test = Y[50:]

In [4]:
beta = cp.Variable(n)
lambd = cp.Parameter(nonneg=True)
problem = cp.Problem(cp.Minimize(objective_fn(X_train, Y_train, beta, lambd)))

lambd_values = np.logspace(-2, 3, 50)
train_errors = []
test_errors = []
beta_values = []
for v in lambd_values:
    lambd.value = v
    problem.solve()
    train_errors.append(mse(X_train, Y_train, beta))
    test_errors.append(mse(X_test, Y_test, beta))
    beta_values.append(beta.value)

In [5]:
beta_values

[array([-1.24299023, -0.7490072 ,  0.35751959, -0.24749316, -0.42419194,
         0.11933709,  1.35058739, -0.54629984,  1.00677019, -0.80631055,
        -0.81709178, -1.88231669,  1.34162416, -1.56632033, -1.48679425,
        -1.49547462,  1.53023474,  0.47826079, -0.24247176, -1.29768692]),
 array([-1.2428833 , -0.74888929,  0.35752512, -0.24752549, -0.42413872,
         0.11939793,  1.35052121, -0.54619375,  1.00658777, -0.80627456,
        -0.8170816 , -1.88222729,  1.34150602, -1.56630033, -1.48675615,
        -1.4953166 ,  1.53005712,  0.47810954, -0.24238777, -1.2976032 ]),
 array([-1.24275052, -0.748742  ,  0.35753351, -0.24756706, -0.42407345,
         0.11947623,  1.35043771, -0.54606215,  1.0063607 , -0.80622963,
        -0.81707052, -1.88211559,  1.34135922, -1.56627473, -1.48670948,
        -1.49511928,  1.52983491,  0.47792174, -0.24228504, -1.29749899]),
 array([-1.24257955, -0.74855279,  0.35754311, -0.24761927, -0.42398872,
         0.11957459,  1.35033169, -0.54589257

In [6]:
# Problem data.
m = 10
n = 5
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)
c = np.ones(n)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [c*x==1]
prob = cp.Problem(objective, constraints)

print("Optimal value", prob.solve())
print("Optimal var")
print(x.value) # A numpy ndarray.

Optimal value 5.234679388552373
Optimal var
[0.17404799 0.22803498 0.15305375 0.31810543 0.12675785]


In [9]:
import cvxopt

ImportError: DLL load failed: The specified module could not be found.

In [10]:
from cvxopt import solvers, matrix, spdiag, sqrt, div

ImportError: DLL load failed: The specified module could not be found.

In [11]:
a=[1,2,3,4]

In [16]:
a.remove(4)

In [18]:
np.arange(-2,6,0.016)

array([-2.00000000e+00, -1.98400000e+00, -1.96800000e+00, -1.95200000e+00,
       -1.93600000e+00, -1.92000000e+00, -1.90400000e+00, -1.88800000e+00,
       -1.87200000e+00, -1.85600000e+00, -1.84000000e+00, -1.82400000e+00,
       -1.80800000e+00, -1.79200000e+00, -1.77600000e+00, -1.76000000e+00,
       -1.74400000e+00, -1.72800000e+00, -1.71200000e+00, -1.69600000e+00,
       -1.68000000e+00, -1.66400000e+00, -1.64800000e+00, -1.63200000e+00,
       -1.61600000e+00, -1.60000000e+00, -1.58400000e+00, -1.56800000e+00,
       -1.55200000e+00, -1.53600000e+00, -1.52000000e+00, -1.50400000e+00,
       -1.48800000e+00, -1.47200000e+00, -1.45600000e+00, -1.44000000e+00,
       -1.42400000e+00, -1.40800000e+00, -1.39200000e+00, -1.37600000e+00,
       -1.36000000e+00, -1.34400000e+00, -1.32800000e+00, -1.31200000e+00,
       -1.29600000e+00, -1.28000000e+00, -1.26400000e+00, -1.24800000e+00,
       -1.23200000e+00, -1.21600000e+00, -1.20000000e+00, -1.18400000e+00,
       -1.16800000e+00, -